name: search_book
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  http: ^0.12.0
  collection: ^1.14.11
  built_value: ^6.3.2 #flutter packages pub run build_runner build
  sealed_unions: ^3.0.2
  tuple: ^1.0.2
  shared_preferences: ^0.4.3
  flutter_html: ^0.9.6
  
  flutter_provider: ^1.1.0+3
  distinct_value_connectable_observable: ^2.0.0
  flutter_bloc_pattern: ^0.0.1+1
  disposebag: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/no_image.png
  fonts:
     - family: NunitoSans
       fonts:
        - asset: assets/NunitoSans-Regular.ttf
     - family: Poppins
       fonts:
        - asset: assets/Poppins-Regular.ttf
