name: demo_bloc_pattern
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  distinct_value_connectable_observable: ^1.0.0+3
  flutter_bloc_pattern: ^0.0.1+1
  http: ^0.12.0
  collection: ^1.14.11
  built_value: ^6.3.2 #flutter packages pub run build_runner build
  sealed_unions: ^3.0.2
  tuple: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/no_image.png
  fonts:
     - family: NunitoSans
       fonts:
         - asset: assets/NunitoSans-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
