name: search_book
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  http: ^0.12.0+2
  collection: ^1.14.11
  built_value: ^7.0.0 #flutter packages pub run build_runner build
  sealed_unions: ^3.0.2+2
  tuple: ^1.0.3
  shared_preferences: ^0.5.6
  flutter_html: ^0.11.1
  
  flutter_provider: ^1.1.0+3
  distinct_value_connectable_stream: ^1.0.3
  flutter_bloc_pattern: ^1.1.0
  disposebag: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/no_image.png
  fonts:
     - family: NunitoSans
       fonts:
        - asset: assets/NunitoSans-Regular.ttf
     - family: Poppins
       fonts:
        - asset: assets/Poppins-Regular.ttf
